---
- name: Check transparent_hugepage exists
  stat:
    path: /sys/kernel/mm/transparent_hugepage
  register: transparent_hugepage_exits

- name: Configure transparent_hugepage/enabled never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
  when: transparent_hugepage_exits.stat.exists

- name: Configure transparent_hugepage/defrag never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
  when: transparent_hugepage_exits.stat.exists

- name: Create hostfiles
  template:
    src: hosts.j2
    dest: /etc/hosts
