all:
  hosts:
    machine1:
      host_name                     : machine2
      zookeeper_id                  : 1
      zookeeper_truststore_path     : .private/certificates/truststore/truststore.jks
      zookeeper_keystore_path       : .private/certificates/zookeeper/zookeeper-keystore-1.jks
      ansible_host                  : 192.168.50.10
      private_key                   : /vagrant/.vagrant/machines/machine2/virtualbox/private_key # local ssh key

    machine2:
      host_name                     : machine2
      zookeeper_id                  : 2
      zookeeper_truststore_path     : .private/certificates/truststore/truststore.jks
      zookeeper_keystore_path       : .private/certificates/zookeeper/zookeeper-keystore-1.jks
      ansible_host                  : 190.120.88.12
      private_key                   : /vagrant/.vagrant/machines/machine2/virtualbox/private_key # local ssh key

    machine3:
      host_name                     : machine3
      zookeeper_id                  : 3
      zookeeper_truststore_path     : .private/certificates/truststore/truststore.jks
      zookeeper_keystore_path       : .private/certificates/zookeeper/zookeeper-keystore-1.jks
      ansible_host                  : 190.120.88.13
      private_key                   : /vagrant/.vagrant/machines/machine3/virtualbox/private_key # local ssh key

  children:
    zookeepernodes:
      hosts:
        machine1:
