---
- name: Lets wait for 9091 to be available.
  wait_for:
    port: 9092
    delay: 5
    timeout: 15

- name: Creating Topics.
  command: "sh /opt/kafka/bin/kafka-topics.sh --create --zookeeper '{% for host in groups['zookeepernodes'] %}{{ hostvars[host]['inventory_hostname'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}'  --replication-factor {{ groups['kafkanodes'] | length }} --partitions 20 --topic {{ item }}"
  with_items: "{{ kafka_topics }}"