package v1alpha1

import (
	"github.com/marcos30004347/kubeapi/pkg/apis/restaurant"
	"k8s.io/apimachinery/pkg/conversion"
)

// Convert_v1alpha1_FooSpec_To_restaurant_FooSpec is an autogenerated conversion function.
func Convert_v1alpha1_FooSpec_To_restaurant_FooSpec(in *FooSpec, out *restaurant.FooSpec, s conversion.Scope) error {
	idx := map[string]int{}
	for _, top := range in.Bar {
		if i, duplicate := idx[top]; duplicate {
			out.Bar[i].Quantity++
			continue
		}
		idx[top] = len(out.Bar)
		out.Bar = append(out.Bar, restaurant.FooBar{
			Name:     top,
			Quantity: 1,
		})
	}

	return nil
}

// Convert_restaurant_FooSpec_To_v1alpha1_FooSpec is an autogenerated conversion function.
func Convert_restaurant_FooSpec_To_v1alpha1_FooSpec(in *restaurant.FooSpec, out *FooSpec, s conversion.Scope) error {
	for i := range in.Bar {
		for j := 0; j < in.Bar[i].Quantity; j++ {
			out.Bar = append(out.Bar, in.Bar[i].Name)
		}
	}

	return nil
}
