// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	restaurant "github.com/marcos30004347/kubeapi/pkg/apis/restaurant"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Bar)(nil), (*restaurant.Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Bar_To_restaurant_Bar(a.(*Bar), b.(*restaurant.Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.Bar)(nil), (*Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_Bar_To_v1alpha1_Bar(a.(*restaurant.Bar), b.(*Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarList)(nil), (*restaurant.BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarList_To_restaurant_BarList(a.(*BarList), b.(*restaurant.BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.BarList)(nil), (*BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_BarList_To_v1alpha1_BarList(a.(*restaurant.BarList), b.(*BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarSpec)(nil), (*restaurant.BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarSpec_To_restaurant_BarSpec(a.(*BarSpec), b.(*restaurant.BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.BarSpec)(nil), (*BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_BarSpec_To_v1alpha1_BarSpec(a.(*restaurant.BarSpec), b.(*BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*restaurant.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Foo_To_restaurant_Foo(a.(*Foo), b.(*restaurant.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_Foo_To_v1alpha1_Foo(a.(*restaurant.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*restaurant.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooList_To_restaurant_FooList(a.(*FooList), b.(*restaurant.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_FooList_To_v1alpha1_FooList(a.(*restaurant.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*restaurant.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooStatus_To_restaurant_FooStatus(a.(*FooStatus), b.(*restaurant.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_FooStatus_To_v1alpha1_FooStatus(a.(*restaurant.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*restaurant.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_FooSpec_To_v1alpha1_FooSpec(a.(*restaurant.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FooSpec)(nil), (*restaurant.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooSpec_To_restaurant_FooSpec(a.(*FooSpec), b.(*restaurant.FooSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Bar_To_restaurant_Bar(in *Bar, out *restaurant.Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BarSpec_To_restaurant_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Bar_To_restaurant_Bar is an autogenerated conversion function.
func Convert_v1alpha1_Bar_To_restaurant_Bar(in *Bar, out *restaurant.Bar, s conversion.Scope) error {
	return autoConvert_v1alpha1_Bar_To_restaurant_Bar(in, out, s)
}

func autoConvert_restaurant_Bar_To_v1alpha1_Bar(in *restaurant.Bar, out *Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_restaurant_BarSpec_To_v1alpha1_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_restaurant_Bar_To_v1alpha1_Bar is an autogenerated conversion function.
func Convert_restaurant_Bar_To_v1alpha1_Bar(in *restaurant.Bar, out *Bar, s conversion.Scope) error {
	return autoConvert_restaurant_Bar_To_v1alpha1_Bar(in, out, s)
}

func autoConvert_v1alpha1_BarList_To_restaurant_BarList(in *BarList, out *restaurant.BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]restaurant.Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BarList_To_restaurant_BarList is an autogenerated conversion function.
func Convert_v1alpha1_BarList_To_restaurant_BarList(in *BarList, out *restaurant.BarList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarList_To_restaurant_BarList(in, out, s)
}

func autoConvert_restaurant_BarList_To_v1alpha1_BarList(in *restaurant.BarList, out *BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_restaurant_BarList_To_v1alpha1_BarList is an autogenerated conversion function.
func Convert_restaurant_BarList_To_v1alpha1_BarList(in *restaurant.BarList, out *BarList, s conversion.Scope) error {
	return autoConvert_restaurant_BarList_To_v1alpha1_BarList(in, out, s)
}

func autoConvert_v1alpha1_BarSpec_To_restaurant_BarSpec(in *BarSpec, out *restaurant.BarSpec, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_v1alpha1_BarSpec_To_restaurant_BarSpec is an autogenerated conversion function.
func Convert_v1alpha1_BarSpec_To_restaurant_BarSpec(in *BarSpec, out *restaurant.BarSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarSpec_To_restaurant_BarSpec(in, out, s)
}

func autoConvert_restaurant_BarSpec_To_v1alpha1_BarSpec(in *restaurant.BarSpec, out *BarSpec, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_restaurant_BarSpec_To_v1alpha1_BarSpec is an autogenerated conversion function.
func Convert_restaurant_BarSpec_To_v1alpha1_BarSpec(in *restaurant.BarSpec, out *BarSpec, s conversion.Scope) error {
	return autoConvert_restaurant_BarSpec_To_v1alpha1_BarSpec(in, out, s)
}

func autoConvert_v1alpha1_Foo_To_restaurant_Foo(in *Foo, out *restaurant.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FooSpec_To_restaurant_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FooStatus_To_restaurant_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Foo_To_restaurant_Foo is an autogenerated conversion function.
func Convert_v1alpha1_Foo_To_restaurant_Foo(in *Foo, out *restaurant.Foo, s conversion.Scope) error {
	return autoConvert_v1alpha1_Foo_To_restaurant_Foo(in, out, s)
}

func autoConvert_restaurant_Foo_To_v1alpha1_Foo(in *restaurant.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_restaurant_FooSpec_To_v1alpha1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_restaurant_FooStatus_To_v1alpha1_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_restaurant_Foo_To_v1alpha1_Foo is an autogenerated conversion function.
func Convert_restaurant_Foo_To_v1alpha1_Foo(in *restaurant.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_restaurant_Foo_To_v1alpha1_Foo(in, out, s)
}

func autoConvert_v1alpha1_FooList_To_restaurant_FooList(in *FooList, out *restaurant.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]restaurant.Foo, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Foo_To_restaurant_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_FooList_To_restaurant_FooList is an autogenerated conversion function.
func Convert_v1alpha1_FooList_To_restaurant_FooList(in *FooList, out *restaurant.FooList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooList_To_restaurant_FooList(in, out, s)
}

func autoConvert_restaurant_FooList_To_v1alpha1_FooList(in *restaurant.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Foo, len(*in))
		for i := range *in {
			if err := Convert_restaurant_Foo_To_v1alpha1_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_restaurant_FooList_To_v1alpha1_FooList is an autogenerated conversion function.
func Convert_restaurant_FooList_To_v1alpha1_FooList(in *restaurant.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_restaurant_FooList_To_v1alpha1_FooList(in, out, s)
}

func autoConvert_v1alpha1_FooSpec_To_restaurant_FooSpec(in *FooSpec, out *restaurant.FooSpec, s conversion.Scope) error {
	// INFO: in.Bar opted out of conversion generation
	return nil
}

func autoConvert_restaurant_FooSpec_To_v1alpha1_FooSpec(in *restaurant.FooSpec, out *FooSpec, s conversion.Scope) error {
	// INFO: in.Bar opted out of conversion generation
	return nil
}

func autoConvert_v1alpha1_FooStatus_To_restaurant_FooStatus(in *FooStatus, out *restaurant.FooStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_v1alpha1_FooStatus_To_restaurant_FooStatus is an autogenerated conversion function.
func Convert_v1alpha1_FooStatus_To_restaurant_FooStatus(in *FooStatus, out *restaurant.FooStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooStatus_To_restaurant_FooStatus(in, out, s)
}

func autoConvert_restaurant_FooStatus_To_v1alpha1_FooStatus(in *restaurant.FooStatus, out *FooStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_restaurant_FooStatus_To_v1alpha1_FooStatus is an autogenerated conversion function.
func Convert_restaurant_FooStatus_To_v1alpha1_FooStatus(in *restaurant.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_restaurant_FooStatus_To_v1alpha1_FooStatus(in, out, s)
}
