---
# https://askubuntu.com/questions/842592/apt-get-fails-on-16-04-or-18-04-installing-mongodb
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4B7C549A058F8B6B

- name: Create the /etc/apt/sources.list.d/mongodb-org-4.2.list file for Ubuntu ({{ ansible_distribution_release }}) 
  shell: echo "deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Mongodb
  apt:
    name: mongodb-org

