---
- name: create log directory for mongodb
  file:
    path: /var/log/mongo
    state: directory
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
    setype: mongod_log_t
    recurse: true

- name: create log file directory for mongodb
  file:
    path: "/var/log/mongo/mongod-{{ inventory_hostname }}.log"
    state: touch
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'

- name: create log directory for mongodb
  file:
    path: /var/log/mongod
    state: directory
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
    setype: mongod_log_t
    recurse: true


- name: create data directory for mongodb
  file:
    path: "{{ mongodb_datadir_prefix }}/mongo-{{ inventory_hostname }}"
    state: directory
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
  delegate_to: '{{ item }}'
  with_items: "{{groups.mongo_servers}}"

- name: Create the mongodb startup file
  template:
    src: mongod.service.j2
    dest: /etc/systemd/system/mongod-{{ inventory_hostname }}.service
    mode: 0644
    seuser: system_u
  delegate_to: '{{ item }}'
  with_items: "{{groups.mongo_servers}}"

- name: Create the mongodb configuration file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod-{{ inventory_hostname }}.conf
  delegate_to: '{{ item }}'
  with_items: "{{groups.mongo_servers}}"


- name: Copy the keyfile for authentication
  copy:
    src: "{{mongodb_key_file_path}}"
    dest: "{{ mongodb_datadir_prefix }}/secret"
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
    mode: 0400
    setype: mongod_var_lib_t
  
- name: Start the mongodb service
  systemd:
    name: mongod-{{ inventory_hostname }}
    state: started
    daemon_reload: yes
    enabled: yes
  delegate_to: '{{ item }}'
  with_items: "{{groups.mongo_servers}}"

- name: Wait mongod
  wait_for:
    port: "{{ mongod_port }}"
    delay: 5

- name: Create the file to initialize the mongod replica set
  template:
    src: mongod_init.js.j2
    dest: /tmp/mongod_init.js

- name: Initialize the replication set
  shell: /usr/bin/mongo "localhost:{{ mongod_port }}/admin" /tmp/mongod_init.js
  ignore_errors: yes
