all:
  hosts:
    machine1:
      host_name                     : machine1
      ansible_host                  : 190.120.88.11
      private_key                   : /vagrant/.vagrant/machines/machine1/virtualbox/private_key # local ssh key
      mongod_port                   : 2700

    machine2:
      host_name                     : machine2
      ansible_host                  : 190.120.88.12
      private_key                   : /vagrant/.vagrant/machines/machine2/virtualbox/private_key # local ssh key
      mongod_port                   : 2701

    machine3:
      host_name                     : machine3
      ansible_host                  : 190.120.88.13
      private_key                   : /vagrant/.vagrant/machines/machine3/virtualbox/private_key # local ssh key
      mongod_port                   : 2702

  children:
    mongo_servers:
      hosts:
        mongo1:
        mongo2:
        mongo3:
    mongoc_servers:
      hosts:
        mongo1:
        mongo2:
        mongo3 :
    mongos_servers:
      hosts:
        mongo1:
        mongo2:
