# zookeeper config
zookeeper_user: zkadmin
zookeeper_group: zkadmin
zookeeper_password: "{{ lookup('env', 'ZOOKEEPER_USER_PASSWORD') }}"

zookeeper_data_store: /tmp/data/zookeeper
zookeeper_logging: /tmp/data/zookeeper_logging

# security options
zookeeper_mTLS: true

zookeeper_keystore_dir: /etc/data/zookeeper/keystore
zookeeper_keystore_password: "{{ lookup('env', 'ZOOKEEPER_KEYSTORE_PASSWORD') }}"

zookeeper_truststore_dir: /etc/data/zookeeper/truststore
zookeeper_truststore_password: "{{ lookup('env', 'TRUSTSTORE_PASSWORD') }}"