# This is an example of a deployment k8s definition.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  # same as in the Service definition
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: "application:latest"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "192Mi"
              cpu: "700m"
          ports:
            - containerPort: 9000
          env:
          # env from secret
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: PASSWAORD

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
# This is defining that anyone that will try
# to access the app-service (only from inside
# the cluser) in the 9000 port
# will be redirected to the 'application' app.
# eq application-service:9000
spec:
  ports:
    - port: 9000
  selector:
    app: application


---
apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  PASSWORD: <Password>


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
