# This is an example of a deployment k8s definition.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx:1.17-alpine
          image: "nginx:latest"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "192Mi"
              cpu: "700m"
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # This make this service accessable from outside the cluster
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx