---
- hosts: mongo_servers
  # serial: 3
  become: true
  roles:
  - {
      role: 'infra/mongodb/playbooks/roles/mongodb',
      flags: ['install', 'mongod']
    }

- hosts: mongoc_servers
  # serial: 3
  become: true
  roles:
  - {
      role: 'infra/mongodb/playbooks/roles/mongodb',
      flags: ['mongoc']
    }

- hosts: mongos_servers
  # serial: 3
  become: true
  roles:
  - {
      role: 'infra/mongodb/playbooks/roles/mongodb',
      flags: ['mongos']
    }

