kafka_user: kafkaadmin
kafka_group: kafkaadmin
kafka_password: "{{ lookup('env', 'KAFKA_USER_PASSWORD') }}"
kafka_data_store: /etc/data/kafka

# security options
kafka_mTLS: true

kafka_keystore_dir: /etc/data/kafka/keystore
kafka_keystore_password: "{{ lookup('env', 'KAFKA_KEYSTORE_PASSWORD') }}"

kafka_truststore_dir: /etc/data/kafka/truststore
kafka_truststore_password: "{{ lookup('env', 'TRUSTSTORE_PASSWORD') }}"