---
zookeeper_mirror: https://www-eu.apache.org/dist/zookeeper
zookeeper_version: 3.6.2
zookeeper_package: apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz

zookeeper_root_dir: /usr/share
zookeeper_install_dir: '{{ zookeeper_root_dir }}/apache-zookeeper-{{ zookeeper_version }}'

zookeeper_dir: '{{ zookeeper_root_dir }}/zookeeper'
zookeeper_log_dir: /var/log/zookeeper

zookeeper_data_dir: /var/lib/zookeeper
zookeeper_data_log_dir: /var/lib/zookeeper
zookeeper_client_port: 2181

zookeeper_id: 1

zookeeper_leader_port: 2888
zookeeper_election_port: 3888

zookeeper_servers: "{{groups['zookeeper-nodes']}}"
zookeeper_environment: {}

zookeeper_user: zkadmin
zookeeper_group: zkadmin
zookeeper_password: "{{ lookup('env', 'ZOOKEEPER_USER_PASSWORD') }}"

zookeeper_data_store: /tmp/data/zookeeper
zookeeper_logging: /tmp/data/zookeeper_logging

# security options
zookeeper_mTLS: true

zookeeper_keystore_dir: /etc/data/zookeeper/keystore
zookeeper_keystore_password: "{{ lookup('env', 'ZOOKEEPER_KEYSTORE_PASSWORD') }}"

zookeeper_truststore_dir: /etc/data/zookeeper/truststore
zookeeper_truststore_password: "{{ lookup('env', 'TRUSTSTORE_PASSWORD') }}"